PREP(addCallRespawnMenu);
PREP(callReinforcements);
PREP(eventKilled);
PREP(eventRespawned);
PREP(handleRespawn);
PREP(setRespawnTickets);
PREP(startRespawnCounter);
PREP(transferLeaderModules);
PREP(updateSides);
