branches:
    - master

name-template: "MalFramework_v$NEXT_MINOR_VERSION"
tag-template: "v$NEXT_MINOR_VERSION"

categories:
    - title: "**ADDED:**"
      labels:
          - "feature"
    - title: "**FIXED:**"
      labels:
          - "bug fix"
    - title: "**IMPROVED:**"
      labels:
          - "enhancement"
    - title: "**CHANGED:**"
      labels:
          - "cleanup"

exclude-labels:
    - "ignore changelog"

change-template: "- $TITLE (#$NUMBER)"
template: |
    ## Change Log Summary

    $CHANGES

replacers:
    # Category titles
    - search: '/\#\# (\*\*(ADDED|FIXED|IMPROVED|CHANGED):\*\*)/g'
      replace: "$1"
