#include "performance_check\initFpsCheck.sqf"
#include "performance_check\fpsNotification.sqf"
#include "admin_menu\addAdminMenu.sqf"
#include "arsenal\addArsenalMenu.sqf"
#include "task_control\addTaskControlMenu.sqf"
#include "curator\createCurator.sqf"
#include "curator\assignCurator.sqf"
#include "curator\addReassignCuratorMenu.sqf"
